name: pibox-searxng

services:
  searxng:
    image: docker.io/searxng/searxng@sha256:f4c8e59de166ed71f6380c0847c312ca51f0d41996e31d0559163b6b09ecde52
    container_name: pi-searxng
    restart: unless-stopped
    ports:
      - "127.0.0.1:6000:8080"
    volumes:
      - "${HOME}/.pi/pibox/services/searxng/config:/etc/searxng"
      - "${HOME}/.pi/pibox/services/searxng/cache:/var/cache/searxng"
    environment:
      SEARXNG_BASE_URL: http://127.0.0.1:6000/
    logging:
      options:
        max-size: "10m"
        max-file: "3"
